- name: Setup Development and Production Hosts
  hosts: all
  become: yes
  tasks:
    - name: Install basic dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git
        - unzip
        - python3
        - python3-pip

    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure SSH key-based authentication is enabled
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
